version: '2'
services:  
  mysql:
      image: mysql:5
      container_name: mysql
      restart: always
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: shopee_tax
        MYSQL_USER: hilmansyafei
        MYSQL_PASSWORD: secret
      ports:
        - 3306:3306
  app:
      build: .
      depends_on:
        - mysql
      links:
        - mysql
