version: "2"
services:
  app:
    container_name: app_shoppie
    restart: always
    working_dir: /usr/src/app 
    build: .
    ports:
      - "3002:3002"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: shopee_tax
      MYSQL_USER: hilmansyafei
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306