version: "2"
services:
  app:
    restart: always
    working_dir: /usr/src/app 
    build: ./
    ports:
      - "3002:3002"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
      PORT: 3002
      DB_CONNECTION_STRING: mysql://root:example@mysql:3306/shopee_tax
      NODE_ENV: Local
  apidoc:
    restart: always
    working_dir: /usr/src/app
    build: ./api_doc
    ports:
      - "3003:3003"
    links:
      - app
    depends_on:
      - app
  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: shopee_tax
      MYSQL_USER: andrymahdison
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306